[application]
nodeURL = "http://${HOST_BESU}:4545"
wsURL = "ws://${HOST_BESU}:4546"
contractAddress = "${CONTRACT_ADDRESS}"
nodeKeyPath = "/opt/secret/key"  
nodeAddressPath = "/opt/secret/nodeAddress"
port = 9001

[security]
permissionsEnabled = false
accountContractAddress = "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"