---

quorumFlags:
  # this will erase keys - so be careful with this on validators
  removeKeysOnDelete: false
  isBootnode: true    # set this to true if this node is a bootnode
  usesBootnodes: true # set this to true if the network you are connecting to use a bootnode/s that are deployed in the cluster 

cluster:
  provider: google  # choose from: google | aws | azure
  cloudNativeServices: false # set to true to use Cloud Native Services (SecretsManager and IAM for AWS; KeyVault & Managed Identities for Azure)
  reclaimPolicy: Delete # set to either Retain or Delete

storage:
  sizeLimit: "20Gi"
  pvcSizeLimit: "20Gi"
  # NOTE: when you set this to Retain, the volume WILL persist after the chart is delete and you need to manually delete it
  reclaimPolicy: "Delete" # choose from: Delete | Retain 

# fixes permissions of volumes becuase besu runs as user `besu` and volumes prefer `root`
volumePermissionsFix:
  - google
  - aws

node:
  besu:
    envBesuOpts: ""
    resources:
      cpuLimit: 0.7
      cpuRequest: 0.35
      memLimit: "2G"
      memRequest: "1G"

    dataPath: "/data/besu"
    keysPath: "/keys"
    privateKeyPath: "/keys/nodekey"
    genesisFilePath: "/etc/genesis/genesis.json"
    logging: INFO
    account:
      password: 'password'
      passwordPath: "/keys/accountPassword"    
    p2p:
      enabled: true
      host: "0.0.0.0"
      port: 60606
      discovery: true
      maxPeers: 25
    rpc:
      enabled: true
      host: "0.0.0.0"
      port: 4545
      api: '["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET", "TRACE", "EEA", "PRIV", "QBFT", "PERM", "TXPOOL"]'
      corsOrigins: '["all"]'
      authenticationEnabled: false
    ws:
      enabled: true
      host: "0.0.0.0"
      port: 4546
      api: '["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET", "TRACE", "EEA", "PRIV", "QBFT", "PERM", "TXPOOL"]'
      authenticationEnabled: false
    graphql:
      enabled: true
      host: "0.0.0.0"
      port: 4547
      corsOrigins: '["all"]'
    txPool:
      retentionHours: 999
      maxSize: 1024
    http:
      allowlist: '["*"]'
    metricsPush:
      enabled: true
      host:
        openprotest: "34.148.88.107"
        protest: "5.5.5.5"
        mainnet: "5.5.5.5"
      port: 9091
      interval: 5
      prometheusJob: "besu"
    permissions:
      enabled: true
      filePath: ""
      nodesContract:
        enabled: true
        address: "0x0000000000000000000000000000000000009999"
      accountsContract:
        enabled: false
        address: "0x0000000000000000000000000000000000008888"

image:
  besu:
    repository: hyperledger/besu
    openprotest:
      tag: 23.4.1
    protest:
      tag: 21.1.6
    mainnet:
      tag: 23.4.1 
    pullPolicy: IfNotPresent
  relay:
    repository: lacnetnetworks/relay-signer-lacchain
    mainnet:
        tag: 1.0.2
    openprotest:
        tag: 1.0.2
    pullPolicy: IfNotPresent
    contract:
       openprotest: 0xa4B5eE2906090ce2cDbf5dfff944db26f397037D
       protest: 0xd4C70F66714D93a4f6553d379288e84bC45053da
       mainnet: 0xEAA5420AF59305c5ecacCB38fcDe70198001d147
  rotation:
    repository: lacnetnetworks/rotation-lacchain
    tag: 1.0.0
    pullPolicy: IfNotPresent
    contract:
       openprotest: 0xB61Fb4d139E3A7F6c520D55e8C63193997866180
       protest: 0xe6BAC76Cf6c46C83E0ff6c51d7C67D2d04cF08E4
       mainnet: 0xed629f027a35B377F0a9Fd4560167e0AA85817Cf
  nginx:
    repository: lacnetnetworks/writer-nginx-lacchain
    tag: 1.0.0
    pullPolicy: IfNotPresent

