---
- name: initializing Orion
  debug:
    msg: initializing Orion

- name: create orion directories
  file:
    path: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { dest: "~/lnet/orion", mode: "0440" }
    - { dest: "~/lnet/orion/keystore", mode: "0440" }
    - { dest: "~/lnet/tmp", mode: "0440" }

- name: copy password to file
  copy:
    dest: ~/lnet/tmp/.account_pass
    content: |
      {{password}}

- name: create certificates
  import_tasks: "init-orion-certificate.yaml"

- name: generate configuration orion file
  template:
    src: "orion.j2"
    dest: "~/lnet/orion/orion.conf"
    force: yes

- name: generate pair keys
  shell: cat ~/lnet/tmp/.account_pass | orion --generatekeys nodeKey
  args:
    chdir: ~/lnet/orion/keystore

- name: Copy Key Public from Orion
  fetch:
    src: ~/lnet/orion/keystore/nodeKey.pub
    dest: "{{ playbook_dir }}/roles/lacchain-writer-node/files/"
    flat: yes

- name: Generate shell script to execute orion service
  template:
    src: "startorion.j2"
    dest: "~/lnet/start-orion.sh"
    mode: 0775
    force: yes

- name: Copy service file to systemd
  copy:
    src: "{{ role_path }}/files/orion.service"
    dest: /lib/systemd/system/orion.service
    mode: 0775

- name: Enable service orion
  service:
    name: orion
    enabled: yes
