---
- name: Update Java version
  import_tasks: "update-java.yaml"

- name: stop Besu
  import_tasks: "stop-node.yaml" 

- name: Update Besu Node
  import_tasks: "update-besu.yaml"

- name: start besu
  import_tasks: "start-node.yaml"

- name: Update relay signer
  import_tasks: "update-relay-signer.yaml"
  when: (networkT == '0') or (networkT == '1') # relay-signer is disabled on pro-testnet

- name: Update nginx configuration
  import_tasks: "update-nginx.yaml"