---
- name: Update Java version
  import_tasks: "update-java.yaml"

- name: stop Besu
  import_tasks: "stop-node.yaml" 

- name: Update Besu Node
  import_tasks: "update-besu.yaml"

- name: Update Relay Signer (if enabled)
  import_tasks: "update-relay-signer.yaml"
  when: install_relay_signer | default(false) | bool

- name: start besu
  import_tasks: "start-node.yaml"
