---
- name: Init besu
  debug:
        msg: "Init Besu"

- name: Get public ip
  shell: dig +short myip.opendns.com @resolver1.opendns.com 2>/dev/null || curl -s --retry 2 icanhazip.com
  register: node_ip

- name: create lacchain directories
  file:
        path: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        state: directory
  with_items:
        - { dest: "~/lnet/data", mode: "0440" }
        - { dest: "~/lnet/logs", mode: "0440" }
        - { dest: "~/lnet/tmp", mode: "0440" }
        - { dest: "~/lnet/scripts", mode: "0440"}

- name: Copy permissioned nodes file
  copy:
        src: "{{ role_path }}/files/permissions_config.toml"
        dest: ~/lnet/tmp/permissions_config.toml
        mode: 0755
  when: bootnode|bool

- name: initializing pantheon from genesis.json
  debug:
        msg: Initializing Pantheon

- name: Copy genesis ibft2.0 file
  copy:
        src: "{{ role_path }}/files/genesis-{{network}}.json"
        dest: ~/lnet/data/genesis.json
        mode: 0755

- name: Generate node key
  shell: pantheon --genesis-file=/root/lnet/data/genesis.json --data-path=/root/lnet/data public-key export --to=/root/lnet/data/bootnode | grep -oE "0x[A-Fa-f0-9]*" | sed 's/0x//'
  register: enode_key

- name: print enode key
  debug:
        msg: enode://{{enode_key.stdout}}@{{node_ip.stdout}}:60606

- name: Generate shell script to execute geth service
  template:
        src: "startpantheon-{{network}}.j2"
        dest: "~/lnet/start-pantheon.sh"
        mode: 0775
        force: yes

        
- name: semanage besu service on centos {{ansible_distribution_major_version}}
  shell: sudo semanage fcontext -a -t bin_t '/root/lnet/start-pantheon.sh'
  when: ((ansible_distribution |lower == 'centos' or ansible_distribution |lower == 'redhat' or ansible_distribution |lower == 'rocky') and ansible_distribution_major_version >= "8")

- name: restorecon besu service on centos {{ansible_distribution_major_version}}
  shell: sudo restorecon -Fv /root/lnet/start-pantheon.sh
  when: ((ansible_distribution |lower == 'centos' or ansible_distribution |lower == 'redhat' or ansible_distribution |lower == 'rocky') and ansible_distribution_major_version >= "8")

- name: Generate Pantheon configuration file
  template:
    src: "pantheon-config-{{network}}.j2"
    dest: "~/lnet/config.toml"
    mode: 0775

- name: Copy service file to systemd
  copy:
        src: "{{ role_path }}/files/pantheon.service"
        dest: /lib/systemd/system/pantheon.service
        mode: 0775

- name: Copy Log configuration file to lacchain
  copy:
        src: "{{ role_path }}/files/log.xml"
        dest: "~/lnet/log.xml"
        mode: 0775

- name: Enable service pantheon
  service:
        name: pantheon
        enabled: yes
